import express from 'express';
import helmet from 'helmet';
import cors from 'cors';
import rateLimit from 'express-rate-limit';
import pinoHttp from 'pino-http';
import { randomUUID } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { config } from './config.js';
import { logger } from './lib/logger.js';
import { errorHandler } from './lib/errors.js';
import { pool, query } from './db/pool.js';
import { startOutboxWorker } from './core/outbox.js';
import { registerOutboxHandlers } from './core/handlers.js';
import { healthSnapshot } from './providers/index.js';

import { healthRouter } from './routes/health.js';
import { authRouter } from './routes/auth.js';
import { accountsRouter } from './routes/accounts.js';
import { paymentsRouter } from './routes/payments.js';
import { transfersRouter } from './routes/transfers.js';
import { kycRouter } from './routes/kyc.js';
import { reviewerRouter } from './routes/reviewer.js';
import { towerRouter } from './routes/tower.js';
import { webhooksRouter } from './routes/webhooks.js';
import { compatRouter } from './routes/compat.js';
import { aiRouter } from './routes/ai.js';

const here = dirname(fileURLToPath(import.meta.url));
const app = express();
app.set('trust proxy', 1);

app.use((req, _res, next) => { req.id = req.get('x-request-id') || randomUUID(); next(); });
app.use(pinoHttp({ logger, genReqId: (req) => req.id }));
app.use(helmet({ contentSecurityPolicy: false, crossOriginEmbedderPolicy: false }));
app.use(cors({
  origin: config.webOrigin.includes('*') ? true : config.webOrigin,
  credentials: true,
  allowedHeaders: ['Content-Type', 'Authorization', 'Idempotency-Key', 'x-request-id']
}));

// keep the raw body for webhook signature checks
app.use(express.json({
  limit: '1mb',
  verify: (req, _res, buf) => { req.rawBody = buf.toString('utf8'); }
}));

app.use('/api/v1', rateLimit({ windowMs: 60_000, limit: 300, standardHeaders: true, legacyHeaders: false }));

app.use('/api/v1', healthRouter);
// Render's health check and the marketing page both poll this shorter path.
app.use('/api', healthRouter);
app.use('/api/v1/auth', authRouter);
app.use('/api/v1/accounts', accountsRouter);
app.use('/api/v1/payments', paymentsRouter);
app.use('/api/v1/transfers', transfersRouter);
app.use('/api/v1/kyc', kycRouter);
app.use('/api/v1/reviewer', reviewerRouter);
app.use('/api/v1/control-tower', towerRouter);
app.use('/api/v1/webhooks', webhooksRouter);
app.use('/api/v1/ai', aiRouter);

// the front ends generated by build.py speak a flat /api surface; this keeps
// them working against the same ledger, with the session enforced
app.use('/api', compatRouter);

// serve the website, web banking and app shell from the same origin
// the built front ends (index, web, app, reviewer console, control tower)
app.use(express.static(join(here, '../../public'), { extensions: ['html'], maxAge: '5m' }));
// the leaner API-native pages, kept reachable for testing the raw surface
app.use('/v2', express.static(join(here, '../../api-web'), { extensions: ['html'], maxAge: '5m' }));
app.get('/api/*', (_req, res) => res.status(404).json({ error: { code: 'not_found', message: 'Unknown endpoint' } }));
app.use(errorHandler(logger));

registerOutboxHandlers();
const outboxTimer = startOutboxWorker(5000);

// periodic rail probe feeds the control tower
const healthTimer = setInterval(async () => {
  try {
    for (const r of await healthSnapshot()) {
      await query('INSERT INTO service_health (component, status, latency_ms, detail) VALUES ($1,$2,$3,$4)',
        [r.component, r.status, r.latencyMs, r.detail]);
    }
    await query(`DELETE FROM service_health WHERE checked_at < now() - interval '7 days'`);
  } catch (err) { logger.error({ err }, 'health probe failed'); }
}, 60_000);

const server = app.listen(config.port, () => {
  logger.info({ port: config.port, env: config.env }, 'ai-digital-bank api listening');
});

async function shutdown(signal) {
  logger.info({ signal }, 'shutting down');
  clearInterval(outboxTimer);
  clearInterval(healthTimer);
  server.close(async () => {
    await pool.end().catch(() => {});
    process.exit(0);
  });
  setTimeout(() => process.exit(1), 10_000).unref();
}
process.on('SIGTERM', () => shutdown('SIGTERM'));
process.on('SIGINT', () => shutdown('SIGINT'));

export { app };
